# These are supported funding model platforms

github: [BrutalBirdie]
custom: ["https://www.gesellschaft-zur-entwicklung-von-dingen.de/", "https://www.indielux.com/", "https://www.ready2plugin.com/"]
